version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MARKET=${MARKET}
      - ALERT_TYPE=${ALERT_TYPE}
      - DISCORD_WEBHOOK_ID=${DISCORD_WEBHOOK_ID}
      - DISCORD_WEBHOOK_TOKEN=${DISCORD_WEBHOOK_TOKEN}
      - TZ=Asia/Bangkok